name: PHPUnit
on:
  push:
    branches:
      - main
      - fix_pipeline
  pull_request:
    branches:
      - main
jobs:
  tests:
    name: Run PHPUnit (PHP ${{ matrix.php-versions }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: [ "8.3" ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ vars.GH_APP_WORKFLOW_TRIGGER_APP_ID }}
          private-key: ${{ secrets.GH_APP_WORKFLOW_TRIGGER_PRIVATE_KEY }}
          owner: Airalo
          repositories: airalo-php-sdk

      - name: Install dependencies
        uses: php-actions/composer@v6
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
          COMPOSER_AUTH: '{"github-oauth": {"github.com": "${{ steps.app-token.outputs.token }}"} }'
        with:
          php_version: ${{ matrix.php-versions }}
          version: 2.x
          dev: yes

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: gd, zip, json, fileinfo, dom, sodium
          coverage: xdebug
      - name: Run PHPUnit
        run: composer phpunit
